services:
  psql:
    container_name: psql
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./backend/
    image: backend
    restart: unless-stopped
    ports:
      - "8000:8000"

  # frontend:
  #   container_name: frontend
  #   build: ./frontend/
  #   image: frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
