CREATE TABLE pet (name VARCHAR(255), type VARCHAR(255), owner INTEGER, id SERIAL PRIMARY KEY );
CREATE TABLE owner (name VARCHAR(255), address VARCHAR(255), phone VARCHAR(255), email VARCHAR(255), id SERIAL PRIMARY KEY );
